Add boundary_reserved_regs option
slothy-optimizer/slothy pull request #104
Opened 2024-11-22 14:49 UTC by dop-amin

Extracted from #61, was introduced originally in 9310140e4b007ecfd1027418ed75516a90b51140.

2024-11-23 04:27 UTC, hanno-becker commented on slothy/core/core.py
> +                self._Add(alloc[r] == False).OnlyEnforceIf(producer.src.pre_var, consumer.pre_var.Not())
This needs a bit more thought and tests to be robust in general:
* There will also be cross-boundary dependencies from non-post to post
* There can be dependencies across loop iterations (say an accumulator being changed in every iteration) that need to be handled correctly as well

2024-11-23 04:29 UTC, hanno-becker requested changes
This is not yet ready to be merged, there are more corner cases to be considered. We should also have some tests for this.

2025-01-03 13:53 UTC, dop-amin commented
I'm closing this as we should rather avoid this situation by pulling most/all of the loop boundary into the loop body as we did in #139 for Armv7M.

2025-01-03 13:53 UTC, dop-amin commented
I'm closing this as we should rather avoid this situation by pulling most/all of the loop boundary into the loop body as we did in #139  for Armv7M.

2025-01-03 13:53 UTC, closed without merging